import { CodeFile, Employee } from '../types';
import { DOCS_AND_TESTS_FILES } from './docsAndTests';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 1,
    name: "Alex Rivera",
    email: "alex.rivera@example.com",
    department: "Engineering",
    salary: 85000,
    date_joined: "2023-01-15"
  },
  {
    id: 2,
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    department: "Human Resources",
    salary: 62000,
    date_joined: "2023-03-20"
  },
  {
    id: 3,
    name: "Marcus Vance",
    email: "marcus.vance@example.com",
    department: "Marketing",
    salary: 68000,
    date_joined: "2023-06-10"
  },
  {
    id: 4,
    name: "Elena Rostova",
    email: "elena.rostova@example.com",
    department: "Engineering",
    salary: 92000,
    date_joined: "2023-09-01"
  },
  {
    id: 5,
    name: "David Chen",
    email: "david.chen@example.com",
    department: "Finance",
    salary: 78000,
    date_joined: "2024-02-18"
  }
];

export const DEPARTMENTS = [
  "Engineering",
  "Human Resources",
  "Marketing",
  "Finance",
  "Sales",
  "Design",
  "Operations"
];

export const CODE_FILES: CodeFile[] = [
  {
    id: "models",
    name: "models.py",
    path: "employees/models.py",
    category: "core",
    description: "Django Model representing Employee with SQLite constraints (unique email, not null fields, decimal salary).",
    language: "python",
    code: `from django.db import models
from django.core.validators import MinValueValidator
from django.utils import timezone


class Employee(models.Model):
    """
    Employee Model representing staff records in the SQLite database.
    Fields:
      - id: Auto-incrementing primary key (provided by Django BigAutoField)
      - name: Full name of the employee (not null)
      - email: Corporate email address (unique constraint, not null)
      - department: Assigned business department (not null)
      - salary: Monthly or annual base compensation (non-negative decimal, not null)
      - date_joined: Formal hire date (not null)
    """

    DEPARTMENT_CHOICES = [
        ('Engineering', 'Engineering'),
        ('Human Resources', 'Human Resources'),
        ('Marketing', 'Marketing'),
        ('Finance', 'Finance'),
        ('Sales', 'Sales'),
        ('Design', 'Design'),
        ('Operations', 'Operations'),
    ]

    # Primary key id is auto-generated by Django
    name = models.CharField(
        max_length=100,
        null=False,
        blank=False,
        help_text="Full legal name of employee"
    )

    # Database constraint: unique=True prevents duplicate email addresses at DB level
    email = models.EmailField(
        max_length=255,
        unique=True,
        null=False,
        blank=False,
        help_text="Unique corporate email address"
    )

    department = models.CharField(
        max_length=50,
        choices=DEPARTMENT_CHOICES,
        null=False,
        blank=False,
        help_text="Department division"
    )

    # Stored as precise fixed-point decimal in SQLite
    salary = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=False,
        blank=False,
        validators=[MinValueValidator(0.01, message="Salary must be greater than zero.")],
        help_text="Base compensation amount"
    )

    date_joined = models.DateField(
        default=timezone.now,
        null=False,
        blank=False,
        help_text="Date the employee joined the company"
    )

    class Meta:
        db_table = 'employees'
        ordering = ['-date_joined', 'name']
        verbose_name = 'Employee'
        verbose_name_plural = 'Employees'

    def __str__(self):
        return f"{self.name} ({self.department}) - {self.email}"
`
  },
  {
    id: "serializers",
    name: "serializers.py",
    path: "employees/serializers.py",
    category: "core",
    description: "Django REST Framework ModelSerializer with field validations and clean error messages.",
    language: "python",
    code: `from rest_framework import serializers
from .models import Employee
from django.utils import timezone


class EmployeeSerializer(serializers.ModelSerializer):
    """
    Data Transfer Object / Serializer for Employee entity.
    Handles deserialization, format conversion, and strict validation.
    """

    class Meta:
        model = Employee
        fields = ['id', 'name', 'email', 'department', 'salary', 'date_joined']
        read_only_fields = ['id']

    def validate_name(self, value):
        """Ensure name contains meaningful characters and minimum length."""
        cleaned_name = value.strip()
        if len(cleaned_name) < 2:
            raise serializers.ValidationError("Employee name must be at least 2 characters long.")
        return cleaned_name

    def validate_email(self, value):
        """Normalize email and verify unique constraint on create or update."""
        normalized_email = value.strip().lower()
        
        # Check uniqueness during update (exclude current instance)
        employee_id = self.instance.id if self.instance else None
        if Employee.objects.filter(email=normalized_email).exclude(id=employee_id).exists():
            raise serializers.ValidationError("An employee with this email address already exists.")
        
        return normalized_email

    def validate_salary(self, value):
        """Ensure salary is positive."""
        if value <= 0:
            raise serializers.ValidationError("Salary must be a positive number greater than 0.")
        return value

    def validate_date_joined(self, value):
        """Prevent future dates for joining."""
        if value > timezone.now().date():
            raise serializers.ValidationError("Date joined cannot be in the future.")
        return value
`
  },
  {
    id: "views",
    name: "views.py",
    path: "employees/views.py",
    category: "core",
    description: "RESTful API ViewSet supporting complete CRUD, search, filtering, and aggregate statistics.",
    language: "python",
    code: `from rest_framework import viewsets, filters, status
from rest_framework.response import Response
from rest_framework.decorators import action
from django.db.models import Avg, Count, Sum
from .models import Employee
from .serializers import EmployeeSerializer


class EmployeeViewSet(viewsets.ModelViewSet):
    """
    API ViewSet providing full RESTful endpoints for Employee resource:
      - GET /api/employees/          -> List all (supports ?search= and ?department=)
      - POST /api/employees/         -> Create new employee
      - GET /api/employees/{id}/     -> Retrieve single employee detail
      - PUT /api/employees/{id}/     -> Full update of employee record
      - PATCH /api/employees/{id}/   -> Partial update of employee record
      - DELETE /api/employees/{id}/  -> Delete employee record
      - GET /api/employees/stats/    -> Custom action for department aggregates
    """
    queryset = Employee.objects.all().order_by('-date_joined')
    serializer_class = EmployeeSerializer
    filter_backends = [filters.SearchFilter, filters.OrderingFilter]
    search_fields = ['name', 'department', 'email']
    ordering_fields = ['name', 'salary', 'date_joined']
    ordering = ['-date_joined']

    def get_queryset(self):
        """
        Extends standard queryset to support custom query params:
          - ?name=<string> (case-insensitive partial match)
          - ?department=<string> (exact match or partial)
          - ?search=<string> (across name, email, department)
        """
        queryset = super().get_queryset()

        # Filter by name if supplied
        name_param = self.request.query_params.get('name', None)
        if name_param:
            queryset = queryset.filter(name__icontains=name_param.strip())

        # Filter by department if supplied
        dept_param = self.request.query_params.get('department', None)
        if dept_param:
            queryset = queryset.filter(department__iexact=dept_param.strip())

        return queryset

    def create(self, request, *args, **kwargs):
        """Custom create to provide explicit 201 Created response formatting."""
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(
            {
                "message": "Employee created successfully.",
                "data": serializer.data
            },
            status=status.HTTP_201_CREATED,
            headers=headers
        )

    def update(self, request, *args, **kwargs):
        """Custom update to return formatted response."""
        partial = kwargs.pop('partial', False)
        instance = self.get_object()
        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        serializer.is_valid(raise_exception=True)
        self.perform_update(serializer)
        return Response(
            {
                "message": "Employee updated successfully.",
                "data": serializer.data
            },
            status=status.HTTP_200_OK
        )

    def destroy(self, request, *args, **kwargs):
        """Custom delete to return explicit confirmation message."""
        instance = self.get_object()
        employee_id = instance.id
        employee_name = instance.name
        self.perform_destroy(instance)
        return Response(
            {
                "message": f"Employee '{employee_name}' (ID: {employee_id}) successfully deleted."
            },
            status=status.HTTP_200_OK
        )

    @action(detail=False, methods=['get'])
    def stats(self, request):
        """
        Custom endpoint: GET /api/employees/stats/
        Returns headcount, average salary, and department breakdown.
        """
        total_count = Employee.objects.count()
        total_payroll = Employee.objects.aggregate(total=Sum('salary'))['total'] or 0
        avg_salary = Employee.objects.aggregate(avg=Avg('salary'))['avg'] or 0
        dept_breakdown = (
            Employee.objects.values('department')
            .annotate(count=Count('id'), avg_salary=Avg('salary'))
            .order_by('-count')
        )

        return Response({
            "total_employees": total_count,
            "total_payroll": float(total_payroll),
            "average_salary": round(float(avg_salary), 2),
            "departments": dept_breakdown
        })
`
  },
  {
    id: "urls_app",
    name: "urls.py (App)",
    path: "employees/urls.py",
    category: "core",
    description: "App-level URL routing using Django REST Framework DefaultRouter.",
    language: "python",
    code: `from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EmployeeViewSet

# Initialize the DRF DefaultRouter
router = DefaultRouter()

# Register the viewset under 'employees'
# Generates:
#   /api/employees/          [GET, POST]
#   /api/employees/{pk}/     [GET, PUT, PATCH, DELETE]
#   /api/employees/stats/    [GET]
router.register(r'employees', EmployeeViewSet, basename='employee')

urlpatterns = [
    path('', include(router.urls)),
]
`
  },
  {
    id: "urls_project",
    name: "urls.py (Project Root)",
    path: "ems_backend/urls.py",
    category: "project",
    description: "Main project routing configuration mapping /admin/ and /api/ prefixes.",
    language: "python",
    code: `from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Built-in Django Admin portal
    path('admin/', admin.site.urls),

    # Employee Management REST API routes
    path('api/', include('employees.urls')),
]
`
  },
  {
    id: "settings",
    name: "settings.py",
    path: "ems_backend/settings.py",
    category: "project",
    description: "Django project settings configuring SQLite, REST Framework, and installed apps.",
    language: "python",
    code: `from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-college-project-ems-key-replace-in-production'

DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party packages
    'rest_framework',

    # Local application
    'employees',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ems_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ems_backend.wsgi.application'

# Database Configuration (SQLite default as requested)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # Open for project evaluation
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}
`
  },
  {
    id: "admin",
    name: "admin.py",
    path: "employees/admin.py",
    category: "core",
    description: "Django Admin panel registration for visual management of SQLite records.",
    language: "python",
    code: `from django.contrib import admin
from .models import Employee


@admin.register(Employee)
class EmployeeAdmin(admin.ModelAdmin):
    """
    Administration view for Employee records inside /admin/.
    """
    list_display = ('id', 'name', 'email', 'department', 'salary', 'date_joined')
    list_filter = ('department', 'date_joined')
    search_fields = ('name', 'email', 'department')
    ordering = ('-date_joined',)
    readonly_fields = ('id',)

    fieldsets = (
        ('Personal Information', {
            'fields': ('name', 'email')
        }),
        ('Employment Details', {
            'fields': ('department', 'salary', 'date_joined')
        }),
    )
`
  },
  {
    id: "requirements",
    name: "requirements.txt",
    path: "requirements.txt",
    category: "project",
    description: "Python dependencies for the Employee Management System.",
    language: "text",
    code: `Django>=4.2.0,<5.1.0
djangorestframework>=3.14.0
django-filter>=23.5
`
  },
  {
    id: "setup",
    name: "SETUP_GUIDE.md",
    path: "SETUP_GUIDE.md",
    category: "docs",
    description: "Complete terminal commands to create, migrate, and run the SQLite Django project.",
    language: "markdown",
    code: `# Employee Management System (DRF + SQLite) Setup Guide

## 1. Create Virtual Environment
\`\`\`bash
# Open terminal in project root
python -m venv venv

# Activate virtual environment
# On macOS/Linux:
source venv/bin/activate
# On Windows:
venv\\Scripts\\activate
\`\`\`

## 2. Install Dependencies
\`\`\`bash
pip install -r requirements.txt
\`\`\`

## 3. Apply Database Migrations (Generates SQLite db.sqlite3)
\`\`\`bash
# Create migration files for the Employee model
python manage.py makemigrations employees

# Run migrations to build the tables in SQLite
python manage.py migrate
\`\`\`

## 4. Create Superuser (For Django Admin)
\`\`\`bash
python manage.py createsuperuser
# Enter username (e.g., admin), email, and password
\`\`\`

## 5. Start the Development Server
\`\`\`bash
python manage.py runserver 8000
\`\`\`
The backend server will run at: \`http://127.0.0.1:8000/\`

## 6. Testing Endpoints with cURL or Postman

### GET all employees
\`\`\`bash
curl -X GET http://127.0.0.1:8000/api/employees/
\`\`\`

### GET with Search (by name or department)
\`\`\`bash
curl -X GET "http://127.0.0.1:8000/api/employees/?search=Alex"
curl -X GET "http://127.0.0.1:8000/api/employees/?department=Engineering"
\`\`\`

### POST a new employee
\`\`\`bash
curl -X POST http://127.0.0.1:8000/api/employees/ \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Jordan Bell",
    "email": "jordan.bell@example.com",
    "department": "Design",
    "salary": 72000.00,
    "date_joined": "2024-03-01"
  }'
\`\`\`

### PUT update employee
\`\`\`bash
curl -X PUT http://127.0.0.1:8000/api/employees/1/ \\
  -H "Content-Type: application/json" \\
  -d '{
    "name": "Alex Rivera",
    "email": "alex.rivera@example.com",
    "department": "Engineering",
    "salary": 90000.00,
    "date_joined": "2023-01-15"
  }'
\`\`\`

### DELETE employee
\`\`\`bash
curl -X DELETE http://127.0.0.1:8000/api/employees/1/
\`\`\`
`
  },
  {
    id: "viva",
    name: "COLLEGE_VIVA_QNA.md",
    path: "COLLEGE_VIVA_QNA.md",
    category: "docs",
    description: "Key technical questions & answers for external examiners and project viva.",
    language: "markdown",
    code: `# College Project Viva & External Examination Q&A

### Q1: Why use Django REST Framework (DRF) instead of vanilla Django?
**Answer:** Vanilla Django is designed to render server-side HTML templates (MVT pattern). Django REST Framework provides specialized tooling for building decoupled RESTful APIs, including ModelSerializers for automatic JSON parsing/validation, ViewSets for standard CRUD routing, content negotiation, pagination, and browsable web APIs.

### Q2: How does SQLite handle constraints like UNIQUE and NOT NULL?
**Answer:** SQLite is a relational, serverless, self-contained SQL database engine. When Django runs migrations, it executes DDL statements like \`CREATE TABLE "employees" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "email" varchar(255) NOT NULL UNIQUE, ...)\`. SQLite strictly enforces uniqueness via B-Tree index lookups; attempting to insert duplicate emails raises an \`IntegrityError\`.

### Q3: What is the role of the Serializer in this architecture?
**Answer:** The Serializer acts as a bi-directional Data Transfer Object (DTO). 
1. **Serialization:** Converts complex Django QuerySet and Model instances into native Python datatypes that can be rendered to JSON.
2. **Deserialization & Validation:** Parses incoming client JSON into Python data while validating field types, required null checks, unique email constraints, and custom business logic (e.g. salary > 0) before committing to SQLite.

### Q4: How are HTTP Status Codes mapped?
- **200 OK:** Successful GET, PUT, or DELETE confirmation.
- **201 Created:** Successful POST request when a new employee record is inserted into SQLite.
- **204 No Content:** Default DRF status when an object is destroyed.
- **400 Bad Request:** Validation failure (duplicate email, empty required field, negative salary).
- **404 Not Found:** When an employee ID does not exist in the database.
`
  },
  ...DOCS_AND_TESTS_FILES
];
